import Head from 'next/head'
import { FC } from 'react'
import s from '../../../styles/css/Home.module.css'
import { Header } from './Header'
import { HeaderImg } from '../HomeLogo/HeaderImg'

interface LayoutProps {
  children: React.ReactNode
}

export const Layout: FC<LayoutProps> = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Podiatry</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='#!' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link href='https://fonts.googleapis.com/css2?family=Macondo&display=swap' />
      </Head>
      <div className='max-w-[1200px] m-auto'>
        <Header />
        <HeaderImg />
      </div>
      {children}
      <footer className={s.footer}>footer</footer>
    </>
  )
}
