import type { NextPage } from 'next'
import Head from 'next/head'
import s from '../styles/css/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={s.container} >
      <Head>
        <title>Podiatry</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={s.main}>
        <div className='text-3xl font-bold ' >
          start
        </div>
      </main>

      <footer className={s.footer}>footer</footer>
    </div>
  )
}

export default Home
